const { Schema } = require("mongoose");

// nested field schema
const OfficialDetailsSchema = new Schema({
  designation: { type: String, required: true },
  offical_phone: [Number],
  official_email: [String],
  salary_per_month: [Number],
  allowance_per_month: [Number],
  working_days_per_month: [Number],
  paid_leaves_per_month: [Number],
  salary_cut_per_day: [Number],
});

const Prototype_Address_Schema = new Schema({
  street: String,
  city: String,
  state: String,
  county: String,
  zipcode: String,
});

const PersonalDetailsSchema = new Schema({
  employee_name: { type: String, required: true },
  gender: [Number],
  date_of_birth: [Number],
  marital_status: [Boolean],
  address: { type: Prototype_Address_Schema },
  phone: [Number],
  email: [String],
});

//export schema
module.exports = {
  AdminSchema: new Schema({
    username: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true },
  }),
  CategorySchema: new Schema({
    category: { type: String, required: true, lowercase: true, unique: true },
    admin_id: { type: String, required: true },
  }),
  TaskSchema: new Schema({
    task_name: { type: String, required: true, lowercase: true, trim: true, unique: true },
    task_remainder_day: { type: Number, required: true },
    description: { type: String, required: true, trim: true },
    admin_id: { type: String, required: true },
  }),
  LocationSchema: new Schema({
    location: { type: String, required: true, lowercase: true, trim: true, unique: true },
    zipcode: { type: Number, required: true },
    admin_id: { type: String, required: true },
  }),
  designation: new Schema({
    designation_name: { type: String, required: true, lowercase: true, trim: true, unique: true },
    salary_per_month: { type: Number, required: true },
    working_days_per_month: { type: Number, required: true },
    paid_leaves_per_year: { type: Number, required: true },
    admin_id: { type: String, required: true },
  }),
  Branches: new Schema({
    email: { type: String, required: true, unique: true },
    username: { type: String, required: true, lowercase: true },
    password: { type: String, required: true },
    branch_name: { type: String, required: true },
    vat_or_trn_number: { type: Number, required: true },
    location: { type: String, required: true },
    date_of_registration: { type: String, required: true },
    address: { type: Prototype_Address_Schema },
    phone: { type: Number, required: true },
    createdOn: { type: Date, default: Date.now },
    admin_id: { type: String, required: true },
  }),
  Notification: new Schema({
    type: { type: String, required: true },
    title: { type: String, required: true },
    msg: { type: String, required: true },
    createdOn: { type: Date, default: Date.now },
    admin_id: { type: String, required: true },
  }),
  EmployeeSchema: new Schema({
    username: { type: String, required: true },
    email: { type: String, unique: true, required: true },
    password: { type: String, required: true },
    updated: { type: Date, default: Date.now },
    official_details: { type: OfficialDetailsSchema, required: true },
    personal_details: { type: PersonalDetailsSchema, required: true },
    role: { type: String, required: true },
  }),
  CompaniesSchema: new Schema({
    company_name: { type: String, required: true, lowercase: true },
    vat_or_trn_number: Number,
    phone: { type: Number, required: true },
    phone2: Number,
    email: { type: String, required: true, lowercase: true },
    email2: { type: String, lowercase: true },
    address: { type: String, required: true, lowercase: true },
    company_type: { type: String, lowercase: true, required: true },
    licence_number: Number,
    mohre_number: Number,
    moi_number: Number,
    quoto: { type: String, lowercase: true },
    company_grade_number: { type: Number, required: true },
    credit_limit: { type: Number, required: true },
    credit_limit_day: { type: Number, required: true },
    existing_credit: { type: Number, default: 0},
    pro_name: { type: String, lowercase: true },
    pro_phone: Number,
    pro_email: { type: String, lowercase: true },
    date_of_registration: { type: Date, default: Date.now() },
    created_by: { type: String, required: true },
    admin_id: { type: String, required: true },
  }),
  CustomerSchema: new Schema({
    customer_type: { type: String, required: true },
    customer_name: { type: String, required: true },
    nationality: String,
    phone: { type: Number, required: true },
    email: { type: String, required: true },
    address: { type: String, required: true },
    date_of_birth: Date,
    gender: { type: String, required: true },
    emirates_id: Number,
    emirates_id_validity: String,
    uid_number: Number,
    passport_number: String,
    passport_validity: Date,
    file_number: Number,
    visa_expiry_date: Date,
    family_book_number: Number,
    family_book_issued_date: Date,
    profession: String,
    daman_policy_number: Number,
    daman_card_number: Number,
    daman_expiry_date: Date,
    credit_limit: { type: Number, required: true },
    credit_limit_day: { type: Number, required: true },
    date_of_registration: { type: Date, default: Date.now() },
    created_by: { type: String, required: true },
    admin_id: { type: String, required: true },
  }),
  Reminder: new Schema({
    service_category: { type: String, required: true, lowercase: true },
    reminder_date: { type: Number, required: true },
    client_type: { type: String, required: true },
    client_id: { type: String, required: true },
    client_name: { type: String, required: true },
    client_phone: { type: String, required: true },
    client_email: { type: String, required: true },
    created_by: { type: String, required: true },
    status: { type: String, required: true },
    admin_id: { type: String, required: true },
  }),
  CompanyBilling: new Schema({
    company_name: { type: String, required: true, trim: true },
    company_id: { type: String, required: true, trim: true },
    bills: [
      {
        particular: { type: String, required: true, trim: true },
        service_type: { type: String, required: true, trim: true },
        bank_account: { type: String, required: true, trim: true },
        typing_charge: { type: Number, required: true },
        govt_charge: { type: Number, required: true },
        transaction_type: { type: String, required: true, trim: true },
        quantity: { type: Number, required: true },
        total_typing_charge: { type: Number, required: true },
        total_govt_charge: { type: Number, required: true },
        id: { type: Number },
      },
    ],
    total_typing_amount: { type: Number, required: true },
    total_govt_amount: { type: Number, required: true },
    grand_total_amount: { type: Number, required: true },
    tax_amount: { type: Number, required: true },
    cross_total_amount: { type: Number, required: true },
    discount: { type: Number, required: true },
    payment_mode: { type: String, required: true },
    bill_amount: { type: Number, required: true },
    payable_amount: { type: Number, required: true},
    paid_amount: {type: Number, required: true},
    balance_amount: { type: Number, required: true},
    payment_details: String,
    remark: String,
    cheque_bank_name: String,
    cheque_number: Number,
    cheque_date: Date,
    card_holder_name: String,
    card_bank_name: String,
    card_number: String,
    credited_bank_account: String,
    created_by: { type: String, required: true },
    createdOn: { type: Date, default: Date.now() },
    admin_id: { type: String, required: true },
  }),
  CustomerBilling: new Schema({
    customer_name: { type: String, required: true, trim: true },
    customer_id: { type: String, required: true, trim: true },
    bills: [
      {
        particular: { type: String, required: true, trim: true },
        service_type: { type: String, required: true, trim: true },
        bank_account: { type: String, required: true, trim: true },
        typing_charge: { type: Number, required: true },
        govt_charge: { type: Number, required: true },
        transaction_type: { type: String, required: true, trim: true },
        quantity: { type: Number, required: true },
        total_typing_charge: { type: Number, required: true },
        total_govt_charge: { type: Number, required: true },
        id: { type: Number },
      },
    ],
    total_typing_amount: { type: Number, required: true },
    total_govt_amount: { type: Number, required: true },
    grand_total_amount: { type: Number, required: true },
    tax_amount: { type: Number, required: true },
    cross_total_amount: { type: Number, required: true },
    discount: { type: Number, required: true },
    payment_mode: { type: String, required: true },
    bill_amount: { type: Number, required: true },
    payable_amount: { type: Number, required: true},
    paid_amount: {type: Number, required: true},
    balance_amount: { type: Number, required: true},
    payment_details: String,
    remark: String,
    cheque_bank_name: String,
    cheque_number: Number,
    cheque_date: Date,
    card_holder_name: String,
    card_bank_name: String,
    card_number: String,
    credited_bank_account: String,
    created_by: { type: String, required: true },
    createdOn: { type: Date, default: Date.now() },
    admin_id: { type: String, required: true },
  }),
  CounterBilling: new Schema({
    counter_name: { type: String, required: true, trim: true },
    counter_phone: { type: Number, required: true },
    counter_email: { type: String, required: true, trim: true },
    counter_address: { type: String, required: true, trim: true },
    bills: [
      {
        particular: { type: String, required: true, trim: true },
        particular_relation: { type: String, required: true, trim: true },
        service_type: { type: String, required: true, trim: true },
        service_id: { type: String, required: true, trim: true },
        bank_account: { type: String, required: true, trim: true },
        typing_charge: { type: Number, required: true },
        govt_charge: { type: Number, required: true },
        transaction_type: { type: String, required: true, trim: true },
        quantity: { type: Number, required: true },
        total_typing_charge: { type: Number, required: true },
        total_govt_charge: { type: Number, required: true },
        id: { type: Number },
      },
    ],
    total_typing_amount: { type: Number, required: true },
    total_govt_amount: { type: Number, required: true },
    grand_total_amount: { type: Number, required: true },
    tax_amount: { type: Number, required: true },
    cross_total_amount: { type: Number, required: true },
    discount: { type: Number, required: true },
    payment_mode: { type: String, required: true },
    bill_amount: { type: Number, required: true },
    payable_amount: { type: Number, required: true},
    paid_amount: {type: Number, required: true},
    balance_amount: { type: Number, required: true},
    payment_details: String,
    remark: String,
    cheque_bank_name: String,
    cheque_number: Number,
    cheque_date: Date,
    card_holder_name: String,
    card_bank_name: String,
    card_number: String,
    credited_bank_account: String,
    created_by: { type: String, required: true },
    createdOn: { type: Date, default: Date.now() },
    admin_id: { type: String, required: true },
  }),
};
